### ISSUE TITLE
💡 A friendly reminder to close the issue if your problem has been solved

### ISSUE THREAD

**Issue by richwill28** [nus-cs2113-AY2122S1/forum#10]
Just a friendly reminder to close the issue if your problem has been solved. This is to avoid convoluting the forum page as things can get messy and complicated real quick. [Example](https://github.com/flutter/flutter/issues).

I will close this issue in a few days. Cheers!

**Comment by okkhoy** [comment]
Good suggestion!
However, I will keep some issue open in public interest 🙂
