### ISSUE TITLE
Gradle failed with 'array initialization' child has incorrect indentation level 16

### ISSUE THREAD

**Issue by alvintan01** [nus-cs2113-AY2122S1/forum#104]
```java
    public void execute(Ui ui, HashMap<String, String> parameters, ArrayList<Medicine> medicines) {
        String[] requiredParameter = {CommandParameters.ID};
        String[] optionalParameters = {CommandParameters.PRICE, CommandParameters.QUANTITY,
                CommandParameters.EXPIRY_DATE, CommandParameters.DESCRIPTION, CommandParameters.NAME,
                CommandParameters.MAX_QUANTITY};
         // More code here
    }
```

For the following code snippet, Gradle would flag that `'array initialization' child has incorrect indentation level 16, expected level should be one of the following: 12, 39, 42.` But according to the coding standards, shouldn't indentation for wrapped lines be 8 spaces? Thus in this case it should be 16 spaces instead of 12?

**Comment by okkhoy** [comment]
After checking with the backend team, there seems to be some discrepancy in the checkstyle specification.
Updating the checkstyle now may create inconvenience for everyone.

So here is the resolution:
- You can either use 4-space indentation for subsequent levels (easier option). [Gradle checks may fail, but marks won't be deducted for code quality in this case.]
- Alternatively, you can tweak the checkstyle file to allow 8-space indentation

**Comment by alvintan01** [comment]
Thanks for your help. I think I'll try to edit the checkstyle file.
