### ISSUE TITLE
Regarding iP - Using OOP concepts

### ISSUE THREAD

**Issue by Kair0s3** [nus-cs2113-AY2122S1/forum#12]
Just a quick general question but, for the individual project, do we have to adhere by the OOP concepts or is that more of a recommended thing?

**Comment by okkhoy** [comment]
Can you please elaborate what you mean?

**Comment by Kair0s3** [comment]
Like for eg. having a "Task" object for iP, is it more of a recommendation to do that?

**Comment by okkhoy** [comment]
hmmm... it is a recommendation now, but becomes a requirement next week when you do inheritance 😅

**Comment by Kair0s3** [comment]
Ouhh, I see, thanks for that clarification!
