### ISSUE TITLE
Should I wrap lines for Markdown?

### ISSUE THREAD

**Issue by richwill28** [nus-cs2113-AY2122S1/forum#121]
[Our coding convention](https://se-education.org/guides/conventions/java/index.html#layout) imposed a hard limit of 120 chars for every line of code.

![image](https://user-images.githubusercontent.com/69445142/139199068-6e041504-f2e3-4b58-bd5a-966eb978edde.png)

However, according to the [SE Markdown coding standard](https://se-education.org/guides/conventions/markdown.html)..

![image](https://user-images.githubusercontent.com/69445142/139198860-6a77e660-2af1-4b8c-b9e8-94148d79d76d.png)

So, which one should I follow?

**Comment by okkhoy** [comment]
Follow both?
Java coding standard applies to Java code; Markdown standard to markdown files.
So to each apply the respective one :-)

**Comment by richwill28** [comment]
Noted.

**Comment by richwill28** [comment]
@okkhoy Follow-up question: Should the lines for Markdown be wrapped at the end of each sentence or paragraph?

**Comment by okkhoy** [comment]
Well, it is a bit subjective. You decide what works the best in your document. I don't think I will go on to scrutinize your MD files.
As such, when you end the paragraph, there is nothing to wrap, so to say!

**Comment by richwill28** [comment]
Closing this issue to keep the forum clean.
