### ISSUE TITLE
Re: Update your JAR, if necessary

### ISSUE THREAD

**Issue by richwill28** [nus-cs2113-AY2122S1/forum#123]
![image](https://user-images.githubusercontent.com/69445142/139376309-362e4654-4bf7-4186-b9b3-b52758a6dc99.png)

Hi @okkhoy, I would like to ask for confirmation regarding this. Do we update *only* the JAR file? Or update the v2.0 release altogether?

**Comment by okkhoy** [comment]
either one is OK.
I will ask students to ensure they picked up the latest one from github.
If you have just one v2.0 but updated the JAR, that would be the latest one anyway.
If you have a v2.0.1 with new JAR, that would be the lastest one.
So according to me both are the same.

Is there anything I missed?

**Comment by richwill28** [comment]
Noted. Thanks for confirming.

**Comment by richwill28** [comment]
Closing this issue to keep the forum clean.
