### ISSUE TITLE
Closing duplicate issues from PE-D

### ISSUE THREAD

**Issue by richwill28** [nus-cs2113-AY2122S1/forum#124]
Are we allowed close duplicate issues from the PE-D?

**Comment by okkhoy** [comment]
Yes. Pl. retain one and close the others by marking them as duplicates of the retained one.

**Comment by okkhoy** [comment]
Just say Duplicate of #<number>

**Comment by AnShengLee** [comment]
So we are not suppose to close PED issues? Even those that we have fixed?

**Comment by okkhoy** [comment]
Oops! that is not what I meant.
Close them as you have fixed the issues. What I said is applicable _before_ working on the fixes 😅

**Comment by richwill28** [comment]
Closing this issue to keep the forum clean.
