### ISSUE TITLE
What is allowed in this Milesone

### ISSUE THREAD

**Issue by andrewtkh1** [nus-cs2113-AY2122S1/forum#126]
Hi Sir,

I noticed that there is a `Note what is allowed in this Milestone:` section. After reading through, I didn't see anything that is "not allowed", only "Strongly Discouraged". 

Did I misread something or is my understanding correct? 

![image](https://user-images.githubusercontent.com/69303287/139588439-5807fdfe-0f07-4ab8-ac96-f0db7465bd73.png)

**Comment by okkhoy** [comment]
Errr.. that line **`Note what is allowed in this milestone:`** was supposed to be removed. 
I have redeployed the site after the correction. 
In general, the guideline from my side is just "strongly discouraged", I am not forbidding anything in the last iteration as such.
