### ISSUE TITLE
Regarding Coursemo questions

### ISSUE THREAD

**Issue by andrewtkh1** [nus-cs2113-AY2122S1/forum#13]
Hi Sir,

For the last question in Coursemology, is there something wrong final test case output in the system? Mainly the "total in local currency..." being on a new line, as the one shown in the CS2113 Website is different from coursemo.
![image](https://user-images.githubusercontent.com/69303287/130311594-690a76db-4b2b-4e93-a14a-37072459cfad.png)
(From Coursemo)

![image](https://user-images.githubusercontent.com/69303287/130311611-6024f95f-6dd0-43f7-8f42-069814cfe311.png)
(From CS2113 site)

**Comment by okkhoy** [comment]
We will check and respond soon.

**Comment by nvbinh15** [comment]
I think the rendering on Coursemology is slightly different and nothing wrong with the test cases.

This is the result when I run locally:

```
$ java Main
Your expenses while overseas?nothing. I lived off my friends all the time.
Expenses in overseas currency:[]
Total in local currency: $0.00
```

And it passes all the test cases.

![Screen Shot 2021-08-21 at 16 28 48](https://user-images.githubusercontent.com/62022886/130315914-6cc3f94d-c7f7-41fb-be21-499ab0020876.png)

**Comment by andrewtkh1** [comment]
Hi Guys,

I think i know the issue. I believe it's mainly due to the formatting of my float output. When the total value is 0, it prints out as "0.0" when the system is expecting "0.00". This can easily be fixed by using `System.out.printf(...)` instead of using `System.out.println(...)`

Thank you Sirs & @nvbinh15 for your input!
