### ISSUE TITLE
Merging of PR with failed CI check

### ISSUE THREAD

**Issue by KishorKumar11** [nus-cs2113-AY2122S1/forum#130]
Hi Prof, not sure if this has been addressed before, but will we be penalized if we accidentally merge a PR which fails the CI checks? 😅 

I understand that it is not a good practice to merge these type of PRs. However, it was due to some minor problem in the `text-ui-test` file that was hard to detect at that time.

**Comment by okkhoy** [comment]
> will we be penalized if we accidentally merge a PR which fails the CI checks?

No.

> I understand that it is not a good practice to merge these type of PRs.

Made me happy 😄

**Comment by KishorKumar11** [comment]
> Made me happy 😄
😆 

Thanks Prof!
