### ISSUE TITLE
Self-invocation vs SLAP

### ISSUE THREAD

**Issue by saravanamani1999** [nus-cs2113-AY2122S1/forum#132]
Hi prof, i remember you mentioning having too many layers of self-invocation would be considered as a design flaw. But what if we use these self-invocations because we want to follow SLAP? Which one should we prioritise, SLAP or keeping the number of self-invocations to the minimum?

**Comment by okkhoy** [comment]
>  would be considered as a design flaw

should be:  **could** be considered as a design flaw

TL;DR
Prioritize SLAP

Interested? read on:

One of the reasons you can have too many self-invocations is when the object is doing too many things and you haven't done the correct abstraction (thus also violating SRP). In such cases, you should consider creating other objects to separate out what each object should be doing.

**Comment by saravanamani1999** [comment]
ahhh okay thanks prof!
