### ISSUE TITLE
Request to use IText 7

### ISSUE THREAD

**Issue by 3m0W33D** [nus-cs2113-AY2122S1/forum#133]
## Library

[IText 7](https://mvnrepository.com/artifact/com.itextpdf/itext7-core/7.2.0)
Dependencies
[SLF4J NOP Binding](https://mvnrepository.com/artifact/org.slf4j/slf4j-nop/2.0.0-alpha5)

## Purpose

Export text to a pdf file.

## License
[AGPL License](http://www.fsf.org/licensing/licenses/agpl-3.0.html)
[MIT License](http://www.opensource.org/licenses/mit-license.php )

**Comment by okkhoy** [comment]
hmmm... is there a different PDF library you can use?
AGPL is another one of those complex licenses... if you can find a different PDF library to export PDF, I suggest you use that?

**Comment by 3m0W33D** [comment]
Hi Prof, previously this library was approved in #111 also with AGPL. This is simply the upgrade version of the same library as IText 5 was deprecated.

**Comment by okkhoy** [comment]
I think I didn't pay full attention then! I will approve this as well. Please ensure you adhere to the license terms 👍 
As such MIT and \*GPL\* are kinda compatible, but the \*GPL\* ones are a bit complex. So do what is necessary to not violate the terms (which you need to figure out 🙂)
