### ISSUE TITLE
UG, DG conversion to PDF

### ISSUE THREAD

**Issue by saravanamani1999** [nus-cs2113-AY2122S1/forum#136]
Hi prof and friends, after the conversion to pdf, our team has issues with not being able to horizontal scroll the code snippets in our UG, it seems like it's not possible to do so on pdf. May i know if anyone has any tips/alternate conversion methods to overcome this issue?

![image_2021-11-07_01-39-08](https://user-images.githubusercontent.com/66838856/140645994-b4bb6c6e-6e9d-4064-80ce-cd7139a1077a.png)

**Comment by okkhoy** [comment]
get a screenshot of the output and use that in the UG?

**Comment by saravanamani1999** [comment]
oh yeah that could work too, thanks prof!
