### ISSUE TITLE
Naming of JAR release

### ISSUE THREAD

**Issue by andrewtkh1** [nus-cs2113-AY2122S1/forum#138]
Hi,

I named my Jar file according to the convention given, but upon uploading it to Git, it automatically removes the `[` & adds a dot.

Original name: `[CS2113-T13-2][LOTS]`

After uploading:
![image](https://user-images.githubusercontent.com/69303287/140651220-79998a86-6e1b-462c-a631-42ea6ebc3565.png)

Is this expected or did i miss a step somewhere?

**Comment by KishorKumar11** [comment]
I believe that the coding convention should be followed only **when submitting the JAR file to LumiNUS**. 

![image](https://user-images.githubusercontent.com/69337196/140667774-58653e90-a8d8-4d46-a91c-952317fc4a00.png)


So you can just rename the downloaded JAR file and submit. The name of JAR in GitHub can just follow the previous JAR files.

**Comment by okkhoy** [comment]
Yes, follow the naming convention for LumiNUS submission
