### ISSUE TITLE
Regarding the inputs for IP

### ISSUE THREAD

**Issue by andrewtkh1** [nus-cs2113-AY2122S1/forum#14]
Hi Sir,

I would like to ask, for IP, can I assume that the user will always key in valid inputs?

E.g, to mark a task as done, one would key in "done 2". Can I assume that the user wont key in things such as "done abc"?

**Comment by okkhoy** [comment]
You can make such assumptions for now. 
In a future increment, we will expect you to do some error handling. At that time, you are required to handle invalid inputs.
However, I strongly suggest you implement _only_ what is required for the current increment.

**Comment by andrewtkh1** [comment]
Understood Sir.

Thank you.
