### ISSUE TITLE
Confusion regarding triage of Ui issues caused by intentional sabotage (from module website)

### ISSUE THREAD

**Issue by yeezao** [nus-cs2113-AY2122S1/forum#141]
Hi prof,

I'd like to clarify this point in the module website (under PE -  Instructions for Reviewing Bug Reports):

![image](https://user-images.githubusercontent.com/61348279/141642290-a6308db8-455b-466a-9940-7a9d84713499.png)

on the point of deliberate sabotage, should it say:

> ..., in which case it should *not* be considered a bug.

instead? Seems a little odd that the parent sections talks about accepting as bugs, and the child subsection says basically the exact same thing.

Thanks in advance!

**Comment by okkhoy** [comment]
Yes.. please read it as should **not** be considered a bug. I will fix the wording on the website in a short while.

Thanks for pointing out!

**Comment by yeezao** [comment]
Thank you prof! :)
