### ISSUE TITLE
In sequence diagrams, are the duplicate entities at the bottom considered as bugs?

### ISSUE THREAD

**Issue by pos0414** [nus-cs2113-AY2122S1/forum#143]
In Plant UML, entities are also added at the bottom by default as shown in the highlighted part below. Can these be considered as bugs? 

![image](https://user-images.githubusercontent.com/47795460/141652184-a43fc98d-6e02-4870-9231-f7504a03dac8.png)

**Comment by okkhoy** [comment]
no.. these are not bugs

**Comment by pos0414** [comment]
Thank you! I'm relieved 😊
