### ISSUE TITLE
Regarding sequence diagram notation

### ISSUE THREAD

**Issue by mayankp291** [nus-cs2113-AY2122S1/forum#148]
Hi Prof,
It is mentioned on the course website that activation bars may be omitted if they do not result in ambiguities or loss of relevant information. However, is it ok to omit activation bars in some parts and show them in others within the same sequence diagram (as shown below)? 

![image](https://user-images.githubusercontent.com/69447074/141832738-57d204c1-2e5c-4706-8ee6-4961d4f8d5d6.png)

**Comment by okkhoy** [comment]
this is not a problem with the notation as such, however, it is better to be uniform with the activation bars.
