### ISSUE TITLE
Missing Issue Response in tester response

### ISSUE THREAD

**Issue by saravanamani1999** [nus-cs2113-AY2122S1/forum#149]
<img width="1181" alt="Screenshot 2021-11-17 at 11 54 07 AM" src="https://user-images.githubusercontent.com/66838856/142131719-f1686c03-caa4-4028-9b50-701a866356af.png">

Hi prof, just to double confirm, some of the issues which I had reported have been sent back to me with missing `issue response` does that mean I can assume the issue has been accepted? or is it an error that its not showing up?

**Comment by okkhoy** [comment]
yes. you can assume that the issue has been accepted (unless they rejected it without a reason!).

**Comment by saravanamani1999** [comment]
ahhh okok thanks prof!
