### ISSUE TITLE
Status of final decision on PE bugs

### ISSUE THREAD

**Issue by yeezao** [nus-cs2113-AY2122S1/forum#150]
Hi prof,

Just out of curiosity - will we be able to see the final decision by the teaching team on the triaging of PE bugs (that is, after Phase 4)? Thank you!

**Comment by okkhoy** [comment]
Hmmm... probably not, because of how we configured CATcher. To maintain the integrity of the data we restrict access after the current phase. If things have changed on CATcher end ('cos it is under active development), I will notify.

**Comment by yeezao** [comment]
Got it, thanks prof! :D
