### ISSUE TITLE
Are all UML diagram bugs considered as severity.VeryLow?

### ISSUE THREAD

**Issue by pos0414** [nus-cs2113-AY2122S1/forum#151]
Hi Prof,

I was not sure if my understanding of severity levels is correct.

I read that if a "flaw does not affect usage", it should be considered as `severity.VeryLow` from the module website.

![image](https://user-images.githubusercontent.com/47795460/142214170-cdc45949-31cb-4638-8e5e-6c56fc5b9bd5.png)

I was not sure if "usage" strictly means the usage of the product. If it is true, then since UML diagrams have nothing to do with the usage of the product, should all UML diagram bugs be considered as `severity.VeryLow`?

**Comment by okkhoy** [comment]
That is untrue. Bug severity of the UML should consider the correctness and how much information is mispresented/misrepresented due to the error.

**Comment by pos0414** [comment]
Oh ok, thank you so much Prof!
