### ISSUE TITLE
Finals open book?

### ISSUE THREAD

**Issue by saravanamani1999** [nus-cs2113-AY2122S1/forum#154]
Hi prof I was just wondering for finals, if it is open book or closed book because on the module website I could not find information regarding this. If its open book, are we allowed to refer to local files on our laptops or are only hard copies of our own notes allowed?

**Comment by okkhoy** [comment]
errr.. I thought I updated it after another student emailed me. let me check again.
it is open book. you can refer to the files, with some restrictions. please wait for the announcement closer to your exam date.
I will fix the website if it is not reflecting my earlier edit.

**Comment by saravanamani1999** [comment]
Alright thanks prof!
