### ISSUE TITLE
Regarding navigability in UML diagrams  

### ISSUE THREAD

**Issue by AnShengLee** [nus-cs2113-AY2122S1/forum#162]
Are solid lines without any arrowheads at all considered bidirectional?

**Comment by andrewtkh1** [comment]
IDT we can talk about we can talk about bidirectional when there is no information on `navigability` provided?

**Comment by okkhoy** [comment]
No, you cannot infer that. You need navigability information

**Comment by AnShengLee** [comment]
Alright thanks all.
