### ISSUE TITLE
Questions regarding JavaDoc comments

### ISSUE THREAD

**Issue by brendanlsz** [nus-cs2113-AY2122S1/forum#163]
Are errors in JavaDoc header comments considered coding standard violations or general errors?

Thank you!

**Comment by okkhoy** [comment]
Can you give an example?

**Comment by brendanlsz** [comment]
For example in this case the '@return' statement is empty:
![image](https://user-images.githubusercontent.com/69447371/143832556-83ab1247-4278-44d0-86bd-c5bcaf7f1eda.png)

**Comment by okkhoy** [comment]
This is more of a coding standard violation.

**Comment by brendanlsz** [comment]
Noted, thanks Prof.
