### ISSUE TITLE
Clarification on ChatBot Customization

### ISSUE THREAD

**Issue by KVignesh122** [nus-cs2113-AY2122S1/forum#18]
Hi, I understand that there is a clause which reads "customize the chatbot name, command/display formats, and even the personality of the chatbot to make your chatbot unique." under Level-1 iP for Week 3. But is this customization only limited to Level-1 or is it also allowed for future Levels/commits.

As of now, I have programmed my chatbot in such a way that it switches between Echo mode and Add task mode when the user types in "change". Likewise, at start up when the chatbot greets, it also asks the user which mode they would like to enter. Are such customizations allowed or will they be marked down by the grading scripts since particular keywords like "change", or "1" / "2" for the modes, change the way my chatbot functions, which I am guessing the grading scripts will not take into account?

**Comment by okkhoy** [comment]
The scripts themselves will not mark you down for doing the you have mentioned here.
However, please ensure that you have good documentation and a way to achieve all the things mentioned in the increments. 
Else, user testing may not find things you did and could evaluate on fewer things than you actually worked on!

**Comment by KVignesh122** [comment]
OK thanks for that comment prof @okkhoy . Where can I find the instructions to create a proper documentation for my chatbot - I believe it is a separate document I have to create right? Or, am I just supposed to insert comments in my code to explain what my codeblocks are doing?

**Comment by okkhoy** [comment]
You need to write a user guide towards the end; you are also required to write code comments. When we talk about documentation, I will elaborate on these items.
@KVignesh122

**Comment by yapjoonsiong** [comment]
@okkhoy Hello prof. I have a question regarding customization as well. In my ChatBot, for adding items to the list, for example adding the item 'lunch', my code requires the user to input 'add lunch' instead of 'lunch' to add to the list. Is this allowed?

**Comment by KVignesh122** [comment]
Ya it's allowed. Just make sure you mention that in the documentation.
