### ISSUE TITLE
Purpose of Exp points

### ISSUE THREAD

**Issue by Nirmaleshwar** [nus-cs2113-AY2122S1/forum#19]
May I know what is the purpose of the experience points on coursemology? Is it something we need to be concerned about before submitting?

**Comment by okkhoy** [comment]
Exp points is associated with a date, which is the deadline to obtain participation points.
It helps you to track that deadline so that your submission can be counted towards participation points. Apart from that no other significance.

**Comment by Nirmaleshwar** [comment]
Oh okay got it Prof. There are two columns though, so I'm assuming we only recieve bonus exp points for submitting before the deadline?

**Comment by okkhoy** [comment]
Nope no bonus points. The second column is Sept 26 (IIRC) and that is the hard deadline; you cannot submit after that.
The first column is what I put there to help you keep track of exercises required for participation.

**Comment by Nirmaleshwar** [comment]
Okay got it prof thanks!
