### ISSUE TITLE
Unable to Run Duke.main()

### ISSUE THREAD

**Issue by serenakemono** [nus-cs2113-AY2122S1/forum#2]
When I tried to run 'Duke.main()', the following error showed up despite having restarted the IntelliJ IDE:

/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=56897:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Users/serena/Desktop/NUS/CEG/AY21:22SEM1/CS2113/ip/out/production/ip Duke
Error: Could not find or load main class Duke
Caused by: java.lang.ClassNotFoundException: Duke

I have set the project SDK to "corretto-11 Amazon Corretto version 11.0.12" and Project language level to "SDK default". May I know what could be the problem with this?

**Comment by okkhoy** [comment]
Please check if you have to build the project again.

**Comment by KVignesh122** [comment]
Did you happen to change the name of the class from Duke to something else? Make sure that the .java file and and the name of the class inside are both Duke.

**Comment by serenakemono** [comment]
> Did you happen to change the name of the class from Duke to something else? Make sure that the .java file and and the name of the class inside are both Duke.

Thank you so much for your help! I don't think I changed the names but I re-downloaded the project to a different directory and it worked. :))

**Comment by serenakemono** [comment]
> Please check if you have to build the project again.

Thank you so much for your help! It is working now. :)
