### ISSUE TITLE
Grading requirements

### ISSUE THREAD

**Issue by xRossKoh** [nus-cs2113-AY2122S1/forum#20]
May I know if the auto-graders grade using the code tagged to each specific tag?

This is because I forgot to push my Level-1 commit to my master branch but only pushed my Level-1 tag. Now that I have completed Level-2, I have pushed Level-2 to my master branch and also pushed the Level-2 tag. Will this be an issue for the auto-grader?

**Comment by okkhoy** [comment]
Err... please push all the relevant commits (and branches in the future) and then push the tags.

**Comment by xRossKoh** [comment]
Understood. But for Level-1 will thr be any issue? The tag is alr present under the tags of my repo

**Comment by okkhoy** [comment]
If you have pushed level 2, which was done after level 1, then the relevant level 1 commits should be pushed automatically**. So it should be fine.

** If you managed to mess things up somehow (like re cloning, doing only level 2 independently, then this is not true)

**Comment by xRossKoh** [comment]
This means that if i continued working on the same codebase from Level-1 for Level-2 and subsequently committed and push the Level-2 codebase, I should be fine right?

**Comment by okkhoy** [comment]
Please read:

> If you have pushed level 2, which was done after level 1, then the relevant level 1 commits should be pushed automatically. So it should be fine.

If still unclear, please highlight which part so that I can be more specific 🙂

**Comment by xRossKoh** [comment]
It's alright. I think the relevant commits are already present within my remote repository. Thank you for your help with this matter. I will close this issue now.
