### ISSUE TITLE
Tags not same as online repo

### ISSUE THREAD

**Issue by joshualeeky** [nus-cs2113-AY2122S1/forum#21]
I am using IntelliJ for git, but when I tag in Intellij it does not seem to update properly on GitHub.

![image](https://user-images.githubusercontent.com/73279392/130448102-64761850-d8fa-44e4-9bae-0997c003fc5f.png)
![image](https://user-images.githubusercontent.com/73279392/130448179-88038c01-e991-49f1-a00e-96c8060f2818.png)

**Comment by richwill28** [comment]
Have you pushed the tag to GitHub after updating it on your local?

**Comment by joshualeeky** [comment]
@richwill28 This checkbox is always ticked and for the drop down I will select "All" whenever I commit and push. Is there another way of pushing the tags?
![image](https://user-images.githubusercontent.com/73279392/130450015-d7f59bf3-2e92-40e2-af4f-f86652579678.png)

**Comment by richwill28** [comment]
I'm not sure about IntelliJ. But for CLI, you can try the following (this will push everything including lightweight tags).
```
git push --tags
```

There are several ways to push tags, each for different situations. For more information, you can refer to this [thread](https://stackoverflow.com/questions/5195859/how-do-you-push-a-tag-to-a-remote-repository-using-git) or the [official documentation](https://git-scm.com/book/en/v2/Git-Basics-Tagging).

**Comment by joshualeeky** [comment]
@richwill28 thanks! I think the issue is that the tags on the online repo existed so i have to delete them first if i am reassigning the tags on Intellij, I managed to resolve it already. Cheers
