### ISSUE TITLE
Commits and other changes are not updated into the iP dashboard

### ISSUE THREAD

**Issue by madhanse** [nus-cs2113-AY2122S1/forum#23]
I have committed and pushed level-0 and level-1 commits into my forked repository. And I have also enabled the issue tracker. But none of them are reflected in the IP dashboard which is concerning for me as it's graded. So, I would like to check whether it's a bug or will it take some time to get updated.

**Comment by okkhoy** [comment]
1. Please look at the timestamp of the page update.
2. In case you made your updates after the timestamp, things will get picked up in the next cycle of the dashboard updates.
3. In general, iP progress dashboard is 2 cycles behind the code dashboard for updates; so you may have to wait.
4. Lastly, click on the (i) icon (see below) to see the explanation.
![image](https://user-images.githubusercontent.com/1023494/130460935-7d98096b-d36f-4ca7-a317-43e764826727.png)

You should find an answer from the above; if even after waiting for 2 days, you don't see an update, then please send me an email with your student number and github ID for me to check.

**Comment by madhanse** [comment]
Though I committed level 0 and level 1 after the timestamp, I have forked and enabled the issue tracker last Friday. So, is this considered 2 cycles behind the code dashboard?

**Comment by okkhoy** [comment]
Please drop me an email with your github username and student number. I will check and update you via email.
