### ISSUE TITLE
Grading of commits

### ISSUE THREAD

**Issue by Nirmaleshwar** [nus-cs2113-AY2122S1/forum#26]
Prof will the auto grader only grade the commits that we've tagged appropriately. For example, I pushed a commit tagged Level-1 with code showing the echo function working properly. Later I push another commit tagged Level-2 with ONLY the add and list function working. 

Or do I have to show both level 1 and 2 functions working together when I push the level 2 code? Because that will take a bit more time to make sure they integrate and work properly.

**Comment by okkhoy** [comment]
You need to build your project in such a way that you evolve its functionality. Which means, you need to ensure proper integration.
However, this will not be tested by the auto-grader, but by the tutor in the tutorial.

**Comment by Nirmaleshwar** [comment]
Understood sir. The reason why I asked is the integration takes time and in the interest of the deadline for the tasks, I wanted to know if this allowed.

So, just to clarify - for the iP tasks required to be checked by the auto grader, we can submit code that only displays the functionality required from the level. But we can continue to work on integrating everything separately to be later reviewed by the tutor during the tutorial?

On that note, do we have to show the code directly to the TA during the tutorial or will he pull it from our fork?

**Comment by okkhoy** [comment]
>So, just to clarify - for the iP tasks required to be checked by the auto grader, we can submit code that only displays the functionality required from the level. But we can continue to work on integrating everything separately to be later reviewed by the tutor during the tutorial?

No. Your understanding of the process is incorrect. 
While there is nothing stopping you from doing it, that is the incorrect approach (unless you are following a branching workflow, and merge feature branch to the main -- which again leads to integration difficulties).

Edit - additions:

You will demonstrate the iP based on what questions we ask you in the tutorial. Code review is a separate process, we will let you know when the time comes for that 🙂

**Comment by Nirmaleshwar** [comment]
Okay got it sir thanks!
