### ISSUE TITLE
Tags in Git

### ISSUE THREAD

**Issue by andrewtkh1** [nus-cs2113-AY2122S1/forum#3]
Hi Sir,

I noticed that we would need to use tags in our future pushes to git. Hence i'm trying it out right now to clarify my understanding. Can I ask, what is the difference between the option of "Working copy parent" & "Specified commit"? 

I only understand that the latter attaches a tag to a specific commit, but what does the former do?
![image](https://user-images.githubusercontent.com/69303287/129567842-348ada23-a345-4e04-8a56-3203c3594701.png)

Also, is this the "tagging" that would be expected of us in the coming projects?

**Comment by okkhoy** [comment]
Working copy parent translates to the latest commit you have just before creating the tag. 

We will talk a bit about tagging in the next lecture.

Yes, this is the tagging you are expected to apply to the various levels/increments in iP from Week3 onwards.

Additional info: Do remember, you need to push the tags as well for marking purposes!

**Comment by andrewtkh1** [comment]
Got it!

For this post, do i "Close this issue" or leave it open?

Many thanks!
