### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by exetr** [nus-cs2113-AY2122S1/forum#31]
Is there a specified extent or level to which we should perform input validation for this project? Or are we supposed to determine the extent ourselves and supply our own justifications?

**Comment by okkhoy** [comment]
No, there is no specified level for validation. As long as the inputs make sense in the context of your program, you can accept it.
If you have some specific restrictions in the input format, you need to take care of those in the validation and document it in the user guide that you will write later (e.g., no spaces allowed)

**Comment by exetr** [comment]
Okay, thank you prof!
