### ISSUE TITLE
Use of Array library

### ISSUE THREAD

**Issue by andrewtkh1** [nus-cs2113-AY2122S1/forum#37]
Hi,

I didn't know that we had to seek permission before we are allowed to use other libraries. In my submission, I've been using the Array library as part of my code. What should I do now?

**Comment by SuibianP** [comment]
I guess the restriction only applies to those not in the Java standard (aka 3rd party libraries)?

**Comment by andrewtkh1** [comment]
So like the the standard, lists, linked list, Trees, etc... are allowed?

**Comment by SuibianP** [comment]
I suppose so? Better wait for Prof to clarify though

**Comment by okkhoy** [comment]
Yup. The "seek permission" rule applies to non- Java standard libraries.
You can use almost everything that Java provides. 
However, if you are using things to send emails, access URL etc., talk to your tutors first!
