### ISSUE TITLE
Collaborative document link

### ISSUE THREAD

**Issue by 3m0W33D** [nus-cs2113-AY2122S1/forum#38]
Hi,

it was mentioned in the TP for week 4 for that we had to submit a link to a folder containing collaborative team documents.
If we are not using google drive, but rather Microsoft SharePoint where the folder can be shared to any with organizational (NUS) email, would that still be acceptable?

**Comment by okkhoy** [comment]
You can share the document publicly by email even in SharePoint. Please generate that link and share the same on teammates.

**Comment by 3m0W33D** [comment]
Hi Prof,

NUS SharePoint, Public is disable by NUS by default, however, I can select share with anyone within Organization can I share the link like this?
![image](https://user-images.githubusercontent.com/26686523/131285131-25386a8e-9802-4e98-86c0-317a999449d3.png)

**Comment by okkhoy** [comment]
Yes. Please use that. I suppose link with public was never available and I was referring to the "People in NUS ..." link.

**Comment by 3m0W33D** [comment]
Ok thanks prof!
