### ISSUE TITLE
Regading Coursemo Q3 Ex3.

### ISSUE THREAD

**Issue by andrewtkh1** [nus-cs2113-AY2122S1/forum#39]
Hi All,

I've been having some issues with Q3 in coursemo. It is the question where you have to print the area of the shape.

The answer being produced by my code seems to be 100% the same as the one in coursemo but it still shows my answer as wrong.

I've double checked to ensure that its not a compile error but to no avail. Did anyone encountered this issue or is it just me?

![image](https://user-images.githubusercontent.com/69303287/131247405-2f4d913c-b36a-414c-b06a-eb76f3bd0ebd.png)
![image](https://user-images.githubusercontent.com/69303287/131247413-64268708-36d7-4250-9a87-07f73cd00234.png)

**Comment by richwill28** [comment]
Not sure if you have already solved the issue, since it is posted 6 hours ago. Nonetheless, this may sound trivial but have you checked that your `Circle` and `Rectangle` are already declared as subclasses of `Shape`? (i.e., using the `extends` keyword)

**Comment by crabnuggets** [comment]
Hi, I have 

> Not sure if you have already solved the issue, since it is posted 6 hours ago. Nonetheless, this may sound trivial but have you checked that your `Circle` and `Rectangle` are already declared as subclasses of `Shape`? (i.e., using the `extends` keyword)

Hi, I am experiencing the same issues as brought up by the OP and I have also declared `Circle` and `Rectangle` as subclasses of `Shape`.

**Comment by andrewtkh1** [comment]
> 
> 
> Not sure if you have already solved the issue, since it is posted 6 hours ago. Nonetheless, this may sound trivial but have you checked that your `Circle` and `Rectangle` are already declared as subclasses of `Shape`? (i.e., using the `extends` keyword)

Hi, no it has not been solved and yes, i've double checked to ensure my classes have been declared properly.

Were you able to pass the test cases?

**Comment by Nirmaleshwar** [comment]
Hi, I faced the same issue. I have checked my code several times. The output is also the same as what coursemo wants but, still getting an error.

**Comment by praj-bellakka** [comment]
Hi, I am facing the same issue. The output on my IDE is identical to the one expected but coursemology is refusing to accept the answer.

**Comment by nvbinh15** [comment]
You should check if there are any extra spaces/newline characters, which may be hard to detect if you build and run your program with IntelliJ. 

Compile and run your program manually with `javac` instead, feed the output to a `.txt` file (e.g. `output.txt`), write a new file of the expected output (e.g. `expected.txt`), and then compare those 2 files by `diff` on Unix-bases OS or `FC` on Windows. Doing so may also detect hidden warnings that IDEs sometimes ignore.

If all seems fine on your local machine, make sure each file on Coursemology has the same content as those on your computer.

**Comment by richwill28** [comment]
> > Not sure if you have already solved the issue, since it is posted 6 hours ago. Nonetheless, this may sound trivial but have you checked that your `Circle` and `Rectangle` are already declared as subclasses of `Shape`? (i.e., using the `extends` keyword)
> 
> Hi, no it has not been solved and yes, i've double checked to ensure my classes have been declared properly.
> 
> Were you able to pass the test cases?

Yes I'm able to pass the test cases. You can try @nvbinh15 idea, since spaces and newline characters are hard to catch.

**Comment by Mick609** [comment]
> You should check if there are any extra spaces/newline characters, which may be hard to detect if you build and run your program with IntelliJ.
> 
> Compile and run your program manually with `javac` instead, feed the output to a `.txt` file (e.g. `output.txt`), write a new file of the expected output (e.g. `expected.txt`), and then compare those 2 files by `diff` on Unix-bases OS or `FC` on Windows. Doing so may also detect hidden warnings that IDEs sometimes ignore.
> 
> If all seems fine on your local machine, make sure each file on Coursemology has the same content as those on your computer.

@praj-bellakka @andrewtkh1 Have you guys tried @nvbinh15 's method? What is the output of the diff command?

**Comment by andrewtkh1** [comment]
> 
> 
> > You should check if there are any extra spaces/newline characters, which may be hard to detect if you build and run your program with IntelliJ.
> > Compile and run your program manually with `javac` instead, feed the output to a `.txt` file (e.g. `output.txt`), write a new file of the expected output (e.g. `expected.txt`), and then compare those 2 files by `diff` on Unix-bases OS or `FC` on Windows. Doing so may also detect hidden warnings that IDEs sometimes ignore.
> > If all seems fine on your local machine, make sure each file on Coursemology has the same content as those on your computer.
> 
> @praj-bellakka @andrewtkh1 Have you guys tried @nvbinh15 's method? What is the output of the diff command?

FC gave me no difference in output. The only main difference i can find is that my actual output ends off at the next line cause i'm using `println(...)` to output. Aside from that, both the FC command and myself can't seem to spot any difference in the outputs.

**Comment by Mick609** [comment]
> > > You should check if there are any extra spaces/newline characters, which may be hard to detect if you build and run your program with IntelliJ.
> > > Compile and run your program manually with `javac` instead, feed the output to a `.txt` file (e.g. `output.txt`), write a new file of the expected output (e.g. `expected.txt`), and then compare those 2 files by `diff` on Unix-bases OS or `FC` on Windows. Doing so may also detect hidden warnings that IDEs sometimes ignore.
> > > If all seems fine on your local machine, make sure each file on Coursemology has the same content as those on your computer.
> > 
> > 
> > @praj-bellakka @andrewtkh1 Have you guys tried @nvbinh15 's method? What is the output of the diff command?
> 
> FC gave me no difference in output. The only main difference i can find is that my actual output ends off at the next line cause i'm using `println(...)` to output. Aside from that, both the FC command and myself can't seem to spot any difference in the outputs.

In this test case, there is a new line (\n) after the last print output (16), so using println() should be fine for producing the correct output. My suggestion is to check if you have too many new lines after the last print output (there should be only one \n). You may also want to check if there is extra space before or after each of your print outputs (in each line). As our friends mentioned above, these differences are hard to catch. The test case for this question checks strictly if your standard output matches the sample output, so one extra space will be considered "different".

**Comment by andrewtkh1** [comment]
> 
> 
> > > > You should check if there are any extra spaces/newline characters, which may be hard to detect if you build and run your program with IntelliJ.
> > > > Compile and run your program manually with `javac` instead, feed the output to a `.txt` file (e.g. `output.txt`), write a new file of the expected output (e.g. `expected.txt`), and then compare those 2 files by `diff` on Unix-bases OS or `FC` on Windows. Doing so may also detect hidden warnings that IDEs sometimes ignore.
> > > > If all seems fine on your local machine, make sure each file on Coursemology has the same content as those on your computer.
> > > 
> > > 
> > > @praj-bellakka @andrewtkh1 Have you guys tried @nvbinh15 's method? What is the output of the diff command?
> > 
> > 
> > FC gave me no difference in output. The only main difference i can find is that my actual output ends off at the next line cause i'm using `println(...)` to output. Aside from that, both the FC command and myself can't seem to spot any difference in the outputs.
> 
> In this test case, there is a new line (\n) after the last print output (16), so using println() should be fine for producing the correct output. My suggestion is to check if you have too many new lines after the last print output (there should be only one \n). You may also want to check if there is extra space before or after each of your print outputs (in each line). As our friends mentioned above, these differences are hard to catch. The test case for this question checks strictly if your standard output matches the sample output, so one extra space will be considered "different".

I've double checked my output multiple times. (I've attached the output txt file below). I suspect it might be due to some compile error? But I'm not sure what might be causing it. The code in Coursemo is 100% the same as the code in my compiler.
[ACTUAL.TXT](https://github.com/nus-cs2113-AY2122S1/forum/files/7074534/ACTUAL.TXT)

**Comment by richwill28** [comment]
I ran `diff output.txt ACTUAL.txt | cat -t` on my terminal.
Note: `output.txt` is my output, and the option `-t` will cause `cat` to show any special characters.

Here is the result.
```console
1,7c1,7
< 78
< 12
< 314
< 78
< 12
< 314
< 16
---
> 78^M
> 12^M
> 314^M
> 78^M
> 12^M
> 314^M
> 16^M

```

Indeed, your output is different and it seems that you have extra characters `^M`. Anyway, I found this [thread](https://unix.stackexchange.com/questions/32001/what-is-m-and-how-do-i-get-rid-of-it/32003) that might be useful to you on how to get rid of the characters.

Honestly I have never seen `^M` before and it seems to originate from Windows (my main machine is Linux btw). Well, I guess I learn something new today 😆.

**Comment by okkhoy** [comment]
This is the thing abt CR and CR+LF.
Check: using `System.out.print("...\n")` vs `System.out.println("...")`

Thanks @richwill28 for giving the details 👍

**Comment by andrewtkh1** [comment]
> 
> 
> I ran `diff output.txt ACTUAL.txt | cat -t` on my terminal.
> Note: `output.txt` is my output, and the option `-t` will cause `cat` to show any special characters.
> 
> Here is the result.
> 
> ```
> 1,7c1,7
> < 78
> < 12
> < 314
> < 78
> < 12
> < 314
> < 16
> ---
> > 78^M
> > 12^M
> > 314^M
> > 78^M
> > 12^M
> > 314^M
> > 16^M
> ```
> 
> Indeed, your output is different and it seems that you have extra characters `^M`. Anyway, I found this [thread](https://unix.stackexchange.com/questions/32001/what-is-m-and-how-do-i-get-rid-of-it/32003) that might be useful to you on how to get rid of the characters.
> 
> Honestly I have never seen `^M` before and it seems to originate from Windows (my main machine is Linux btw). Well, I guess I learn something new today 😆.

OMG. Thank you! Windows does not pick that up.... I'll have to go search thru how to remove that and see how to get it to display on windows machine too.

**Comment by okkhoy** [comment]
> I'll have to go search thru how to remove that and see how to get it to display on windows machine too

Aaah! no.. 

Use the most appropriate print statement (which I want you to figure out)

**Comment by andrewtkh1** [comment]
> 
> 
> > I'll have to go search thru how to remove that and see how to get it to display on windows machine too
> 
> Aaah! no..
> 
> Use the most appropriate print statement (which I want you to figure out)

THANK YOU SIR! Was wrecking my mind since ytd and now i can finally rest peacefully.

**SOLUTION**:
https://medium.com/@wik2kassa/handling-crlf-and-lf-platform-independent-new-lines-in-java-a08fc07ca746

**Comment by andrewtkh1** [comment]
> 
> 
> > I'll have to go search thru how to remove that and see how to get it to display on windows machine too
> 
> Aaah! no..
> 
> Use the most appropriate print statement (which I want you to figure out)

I tried both `println(...)` and `print(... \n)`. none of them passed the test case.

A quick google said to use `System.lineSeperator()` as this will provide you with whatever the current system is using.

**Comment by okkhoy** [comment]
Strange.. `println()` vs `print()` should have solved the problem! 
Did `System.lineSeparator()` solve it?

**Comment by andrewtkh1** [comment]
> 
> 
> Strange.. `println()` vs `print()` should have solved the problem!
> Did `System.lineSeparator()` solve it?

Nope. Neither solved it. Would you like me to drop my code here?

**Comment by crabnuggets** [comment]
I have used `println()` and it did not solve the problem. I ended up using `System.lineSeparator()` and it solved the issue.

**Comment by okkhoy** [comment]
@andrewtkh1  please work with @Mick609  on your submission.

**Comment by andrewtkh1** [comment]
@Mick609 I've tried stripping the string before printing, tried multiple combinations of using println, print, "\n", `System.lineSeparator()`, not printing the last \n, etc.. But all seem to giving the wrong answer. I'm not sure what am i missing out on.

**Comment by Mick609** [comment]
> @Mick609 I've tried stripping the string before printing, tried multiple combinations of using println, print, "\n", `System.lineSeparator()`, not printing the last \n, etc.. But all seem to giving the wrong answer. I'm not sure what am i missing out on.

If this is the case, please send me your code for this question privately so I can have a look of your code in detail. You may contact me via mingqian@u.nus.edu . Please do NOT share your code publicly online.

**Comment by andrewtkh1** [comment]
Hi all,

The issue has been resolve. The main issue was that Coursemo was searching for the function `area()` in my code but i had created another function called `getArea()` to perform the task of `area()`. As such, Coursemo treated as though my code was incorrect.
