### ISSUE TITLE
git commit email config requirement

### ISSUE THREAD

**Issue by SuibianP** [nus-cs2113-AY2122S1/forum#4]
Is it required to set the email to NUS Webmail, or whatever email will do?

**Comment by okkhoy** [comment]
There are two things to consider here.
1. On `GitHub`, you are required to provide an email -- I suggest you provide your school email address to get student benefits
2. On `git` you are required to give an email address for the using `git config user.email <your email address>` in the command line. You can use any email address here; but for GitHub to record your contributions it may be useful to use the same email address you have given in the above step. (Do note that our tools don't depend on this. This is to showcase your work to outside world)
