### ISSUE TITLE
Couldn't find base repository

### ISSUE THREAD

**Issue by DuckWillow** [nus-cs2113-AY2122S1/forum#40]
Remember to give sufficient details e.g.,
* Your development environment (IntelliJ version, Java version, OS, ...)
* Relevant code, error message, stack trace
* Relevant code snippet (an example given below), or link to the relevant code on your GitHub repo

```java
String value = "Some code here"
```

:bulb: You can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format your text
![image](https://user-images.githubusercontent.com/71874189/131320609-ef6038ba-6ca9-40ad-bd25-73f11a69e047.png)

I could find the base repository begin with se-edu/samplerepo.

**Comment by okkhoy** [comment]
There are too many forks, type in se-edu in the filter repos box, you can find it:
![image](https://user-images.githubusercontent.com/1023494/131321508-9df8fbe7-e2b1-4428-907f-50aa1dca5e02.png)

**Comment by DuckWillow** [comment]
![image](https://user-images.githubusercontent.com/71874189/131343149-59f5d061-6839-430f-8754-a325a262c766.png)

still can not find :(

**Comment by DuckWillow** [comment]
Am I on the correct page? I mean I enter the pull request from:
my profile-repositories-[my name]ip-pull request?

**Comment by DuckWillow** [comment]
I see other people are using nus-cs2113-AY2122S1/ip as the base repository, maybe I just follow them first.

**Comment by okkhoy** [comment]
Errr... please specify what you want to do?
In your first screenshot, you showed this:
![image](https://user-images.githubusercontent.com/1023494/131359518-976b0d22-952d-402a-b1fb-0edeb2b7acb8.png)
So I assumed you are talking about the sample repo for PR practice.

If that is not what you are looking for, then my answer earlier is meaningless..

**Comment by DuckWillow** [comment]
Yes, I want to create a Pull Request using base repository: se-edu/samplerepo-pr-practice. But I just couldn't find such an option to use.
I was following the individual project week 4, the first guide.

**Comment by okkhoy** [comment]
Hmmmm.. in which case, you started off with the wrong repo:
![image](https://user-images.githubusercontent.com/1023494/131419863-7fab2258-7d85-402e-925d-439c900787e4.png)

You are looking at the iP repository.

You should fork the samplerepo-pr-practice repository to get what you want:
![image](https://user-images.githubusercontent.com/1023494/131419949-e2b0dbcc-058f-48b8-adeb-796136de1040.png)
The link is just above the description screenshot (left side) you have given

**Comment by SuibianP** [comment]
Since pull requests are mainly meant for merging changes upstream, there is no point in creating one between branches that diverge from the very beginning. In other words, it requires common history (ancestor commit) between base and compare branches.

**Comment by DuckWillow** [comment]
Thank you okkhoy, now I find the samplerepo-pr-practice! I was confused about the repos.
