### ISSUE TITLE
For A-TextUiTesting, 'FC' is not recognized error

### ISSUE THREAD

**Issue by teoziyiivy** [nus-cs2113-AY2122S1/forum#50]
I am not able to run line 21 of the runtest.bat. Instead it returns the error:

```
'FC' is not recognized as an internal or external command,
operable program or batch file.
```

However, the lines of code above still run properly so my ACTUAL.TXT file is still created.

**Comment by okkhoy** [comment]
Can you post the full output after running `runtest.bat`?

**Comment by teoziyiivy** [comment]
`cmd.exe /c runtest.bat
'FC' is not recognized as an internal or external command,
operable program or batch file.

Process finished with exit code 1`

This is the output I got.

**Comment by okkhoy** [comment]
Hmmm, just to ensure, are you using a Windows machine? If it's a Mac or Linux, you need to use the `runtest.sh` file.

If it is on Windows, it could be the case that your PATH is messed up.
Can you post the output of this command: `echo %PATH%` when you run it on the command prompt?


Edit:
I cloned your repo, things seem to work fine on my machine (except that ACTUAL and EXPECTED don't match, but that is not the concern here)

**Comment by teoziyiivy** [comment]
`C:\Users\teozi>echo %PATH%
C:\Users\teozi\AppData\Local\Atlassian\SourceTree\git_local\bin;D:\NUS\Sem3\CS2113\jdk11.0.12_7\bin;C:\Users\teozi\AppData\Roaming\Microsoft
`

This is the output I have and yes I am using a Windows machine.

**Comment by okkhoy** [comment]
Hmmm... it looks like you removed the windows folders from the PATH. 

How did you set the path? 

You can try adding the following back to the PATH (edit the variable, not set it directly):
```C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\
```

These are some Windows defaults.

**Comment by teoziyiivy** [comment]
I manually added it to the System variables in environmental variables. 

I added the defaults but the program still outputs the same error as before?

**Comment by okkhoy** [comment]
1. need to them to the PATH variable; not System
2. you need to close the current cmd prompt and open another one to see the changes.

**Comment by teoziyiivy** [comment]
Ah yeah I meant the PATH variable under system variables in the environmental variables.

I reopened cmd after every change.

My echo now outputs:
`C:\Users\teozi>echo %PATH%
C:\Users\teozi\AppData\Local\Atlassian\SourceTree\git_local\bin;D:\NUS\Sem3\CS2113\jdk11.0.12_7\bin;C:\Users\teozi\AppData\Roaming\Microsoft;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;`

However trying to run the runtest.bat file still outputs the same error in my newly opened cmd:

`D:\NUS\Sem3\CS2113\ip\text-ui-test>D:\NUS\Sem3\CS2113\ip\text-ui-test\runtest.bat
'FC' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by okkhoy** [comment]
Can you check running just FC on a new command prompt?
If FC can be found, you get something like this:

```
C:\>FC
FC: Insufficient number of file specifications

C:\>
```

Did you use the `SwitchJava.bat` given on LumiNUS before running the `runtest.bat`

If so, have you ensured that the PATH variable is set appropriately there (as in not replacing the existing PATH)?

If all of these fail, pls ping me after the lecture tomorrow, we will try to fix it there.

**Comment by teoziyiivy** [comment]
Yeah I've used the SwitchJava.bat but FC is still not recognised.
`C:\Users\teozi>switchJava.bat
Java home set to: D:\NUS\Sem3\CS2113\jdk11.0.12_7
Java 11 activated
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment Corretto-11.0.12.7.1 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.12.7.1 (build 11.0.12+7-LTS, mixed mode)
`
And my path is set to D:\NUS\Sem3\CS2113\jdk11.0.12_7 as well.

Thanks for the help! I will ping you after the lecture :)
