### ISSUE TITLE
Regarding the iP progress dashboard

### ISSUE THREAD

**Issue by DuckWillow** [nus-cs2113-AY2122S1/forum#51]
![image](https://user-images.githubusercontent.com/71874189/131878727-affad79f-7ee9-482e-9ce8-f2a75bf2ae2f.png)

I checked my progress and found something I miss. What is this trackor?

**Comment by okkhoy** [comment]
You can click on the (i) icon beside your number to see what it means

**Comment by DuckWillow** [comment]
> You can click on the (i) icon beside your number to see what it means

Thank you! I have successfully added the issue trackor.
