### ISSUE TITLE
Merge on Intellij caused fast forward merge

### ISSUE THREAD

**Issue by KVignesh122** [nus-cs2113-AY2122S1/forum#53]
I have been using the git functions available on Intellij all these while due to ease-of-use. However, today when I clicked merge option on the Intellij platform, I think it did a fast forward merge. There was no option for me to like choose whether or not to do this type of merge.

My current SourceTree looks like this:
<img width="1280" alt="Screenshot 2021-09-06 at 5 01 06 PM" src="https://user-images.githubusercontent.com/55841532/132190297-57c6313f-1cc0-462f-bdcc-9abb5e378af0.png">

I had actually created the branch-Level-5 at "A-CodeQuality" tag and worked on it since then before merging. So, how do I rectify this situation for the iP submission? I have not pushed my files to the remote repo yet.

**Comment by richwill28** [comment]
Never experienced this issue before, but you can take a look at [this thread](https://stackoverflow.com/a/14308631).

**Comment by richwill28** [comment]
To add on, in case anyone is using CLI, `git merge` will fast-forward by default. To disable it, simply use `git merge --no-ff branch`. 

Note: [Reference](https://git-scm.com/docs/git-merge#Documentation/git-merge.txt---ff).

**Comment by KVignesh122** [comment]
Yup, I had checked out that same thread but in it, the person who posted the problem mentioned that they already pushed the file to the remote repo. I could do the same and then try out the suggested method, but I am just making sure this will not result in some kinda problem with the grading scripts. Should I push my repo to the remote as it is and then proceed?

**Comment by richwill28** [comment]
> Yup, I had checked out that same thread but in it, the person who posted the problem mentioned that they already pushed the file to the remote repo. I could do the same and then try out the suggested method, but I am just making sure this will not result in some kinda problem with the grading scripts. Should I push my repo to the remote as it is and then proceed?

Since you haven't pushed to GitHub yet, I think it is safer to try? Since it will only affect the git history on your local machine. I actually tried recreating the issue, and the suggested method seems to be working fine.

**Comment by SuibianP** [comment]
To add on to the discussion above, you can rewrite your repository as you wish even if you have already pushed to the remote. You may need to use `-f` when pushing and it is generally bad practice, but it is possible and should not interfere with the grading script.
