### ISSUE TITLE
💡 Hacktoberfest 2021

### ISSUE THREAD

**Issue by richwill28** [nus-cs2113-AY2122S1/forum#57]
Hi folks, [Hacktoberfest 2021](https://hacktoberfest.digitalocean.com/) will begin in 20 days. Since we will be working on a team and making many pull requests in this module, you might as well join the event. All you need to do is to label your repository with the `hacktoberfest` topic and create 4 new pull requests. Of course you can also do an individual pull request to public repositories. This way you can experience first-hand and learn more about the open source community. Btw, the first 55,000 participants can earn a free T-shirt. 😝

**Comment by okkhoy** [comment]
Does working on your TP qualify you? If it does, it will be nice 🙂

**Comment by richwill28** [comment]
> Does working on your TP qualify you? If it does, it will be nice 🙂

Pretty sure all public repositories do qualify. Not a founder of Hacktoberfest myself, but if it doesn't, this is a good chance for everyone to learn how to create good quality PRs anyway. 😊

**Comment by SuibianP** [comment]
I think any public repo should qualify unless they are for the mere purpose of creating PRs. Participated last year and it was indeed good learning opportunity :) Thanks @richwill28 for the reminder!

**Comment by richwill28** [comment]
PSA: Hacktoberfest has started 🎉

To join you can either:

* Label your PRs with the label `hacktoberfest-accepted` (recommended) or;
* Add the `hacktoberfest` topic to the repository (not as recommended, because other people might contribute to your team's repo and you will have to reject their PR)

**Comment by richwill28** [comment]
Closing this issue to keep the forum clean.
