### ISSUE TITLE
Request to use Finnhub API to retrieve real-time market data for tP

### ISSUE THREAD

**Issue by KVignesh122** [nus-cs2113-AY2122S1/forum#58]
## tP Idea
Given a hectic schedule for many investors and traders, our tP product aims to provide them with a simple CLI software to store the instruments they are following or wanting to open a trade in.

## Proposed API usage
[Finnhub API](https://finnhub.io/)
Given the frequently changing nature of market prices and other financial data, it is important that our product also provides real-time financial data to the user. Therefore, we would like to use the data provided by Finnhub API.

## Purpose
The API provides many crucial financial data like the current market price, company profile, etc. The full list of functionalities can be found in the documentation: https://finnhub.io/docs/api/introduction . We will incorporate only the necessary data into our code.

## License
Using the free plan for personal use: https://finnhub.io/pricing .
Terms: https://finnhub.io/terms-of-service .

**Comment by okkhoy** [comment]
Can you please check with them about your use case for their API, and get a confirmation in writing?
Your project will be in the public domain, not sure if the "strictly personal use" applies to it.
Better to be safe than sorry. I am generally wary about stock/bitcoin API.

Not approved, yet!

**Comment by richwill28** [comment]
In case you cannot use Finnhub, you can take a look at alternative like [Alpha Vantage](https://www.alphavantage.co/) as it seems to support academic usage. The free membership kinda sucks though because you are limited to 5 requests per minute. Not sure if this is compatible with Gradle so have to check with @okkhoy as well.

**Comment by KVignesh122** [comment]
> Can you please check with them about your use case for their API, and get a confirmation in writing?
> Your project will be in the public domain, not sure if the "strictly personal use" applies to it.
> Better to be safe than sorry. I am generally wary about stock/bitcoin API.
> 
> Not approved, yet!

Good day prof. Thanks for your speedy reply on the issue. My team has re-evaluated our need for an API and we have concluded that we can proceed forward with our tP idea even without the API data. As in, our product idea has been tweaked to remove the need for real-time data. We decided that it is better to have the user to input all the data s/he wants to monitor through our CLI programme instead of trying to incorporate the Finnhub API.

The reasons for retreating our proposal for an API:
1) This component only value-adds to our feature but that does not necessarily contribute to higher marks, since the objective of the tP is to assess the fitting in of all product features, how well value proposition and target user needs were met. Hence, my teammates felt that we can still do well and have our tP meet our value proposition without real-time API.
2) Unnecessary work involved in parsing the data for the small number of information fields we need in comparison to the large amount of data the API provides.
3) Concerns raised by teammates about the uncertainty of future tP demands/deliverables and possibility of the constraints of the Finnhub API interfering with our ability to do well in unit testing and other related assessments.
4) Some team members are not confident with the http protocols and coding out a http client in Java.

**Comment by KVignesh122** [comment]
> In case you cannot use Finnhub, you can take a look at alternative like [Alpha Vantage](https://www.alphavantage.co/) as it seems to support academic usage. The free membership kinda sucks though because you are limited to 5 requests per minute. Not sure if this is compatible with Gradle so have to check with @okkhoy as well.

Hi Richard, thanks for your input. Alphavantage was the initial API we were relying on actually. To circumvent the 5 requests per minute, our team tried cycling the API token key in between 4 possible keys, switching from one key to another every 3 requests made. However, that idea didn't work and we were still able to have 5 reqs/min. Our TA advised us that this will be a hindarance later on when unit testing. So that's why we proposed Finnhub instead.

**Comment by okkhoy** [comment]
> Good day prof. Thanks for your speedy reply on the issue. My team has re-evaluated our need for an API and we have concluded that we can proceed forward with our tP idea even without the API data. As in, our product idea has been tweaked to remove the need for real-time data. We decided that it is better to have the user to input all the data s/he wants to monitor through our CLI programme instead of trying to incorporate the Finnhub API.
> 
> The reasons for retreating our proposal for an API:
> 
> 1. This component only value-adds to our feature but that does not necessarily contribute to higher marks, since the objective of the tP is to assess the fitting in of all product features, how well value proposition and target user needs were met. Hence, my teammates felt that we can still do well and have our tP meet our value proposition without real-time API.
> 2. Unnecessary work involved in parsing the data for the small number of information fields we need in comparison to the large amount of data the API provides.
> 3. Concerns raised by teammates about the uncertainty of future tP demands/deliverables and possibility of the constraints of the Finnhub API interfering with our ability to do well in unit testing and other related assessments.
> 4. Some team members are not confident with the http protocols and coding out a http client in Java.

I see! OK. If there is something specific you want to include in your application, you can consider offline data that may be available for academic use, instead of using the API.

> Our TA advised us that this will be a hindrance later on when unit testing. So that's why we proposed Finnhub instead.

Yes, this is true, not just for unit-testing, but for the final testing session (PE) as well.
