### ISSUE TITLE
Week 6 suggested pre-tutorial preparations GitHub link down

### ISSUE THREAD

**Issue by t-l-xin** [nus-cs2113-AY2122S1/forum#61]
Hi prof,

Under Week 6 tutorial: Demo debugging in an IDE, Suggested pre-tutorial preparations, there is a GitHub link that we are supposed to clone the repo from, however the link seems to be down.

[https://nus-cs2113-ay2122s1.github.io/website/schedule/week6/tutorial.html
](https://nus-cs2113-ay2122s1.github.io/website/schedule/week6/tutorial.html
)
Link that seems to be down:
[https://github.com/nus-cs2113-AY2122S1/personbook
](https://github.com/nus-cs2113-AY2122S1/personbook
)

**Comment by okkhoy** [comment]
Ah.. yes.. I haven't set up the Week 6 thingy fully 😄, should be doing that tomorrow noon-ish

**Comment by t-l-xin** [comment]
okay, thanks prof!
