### ISSUE TITLE
Luminus Quiz - Post-Quiz Feedback not viewable

### ISSUE THREAD

**Issue by yeezao** [nus-cs2113-AY2122S1/forum#62]
I just completed the Week 6 Luminus Quiz, but I'm unable to see the marking for the quiz after, even though the settings shown (at least to me) seem to suggest that it should be viewable.

![image](https://user-images.githubusercontent.com/61348279/132897426-b5552f91-eea9-4b99-adb1-efb922a832f8.png)

I've checked my email submission receipt, nothing as well.

Is it intended that students aren't able to see their post-quiz feedback? Thanks!

**Comment by okkhoy** [comment]
It will be visible once the quiz closes.

**Comment by yeezao** [comment]
Thank you!
