### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by andrewtkh1** [nus-cs2113-AY2122S1/forum#63]
Hi Sir,

Are there any "rules" when using try-catch that does not allow me to catch all the exceptions in under 1 catch block?

E.g,

`try {
 ...
} catch (Exception e) {
 ...
}`

**Comment by richwill28** [comment]
Sometimes we just want to focus on the main logic of the program and forget about exceptions. However, since Java uses checked exceptions, you are forced to deal with them, otherwise your code will not compile. However, doing this..

```java
try {
  // your code
} catch (Exception e) {
  // do nothing
}
```

is a horrible idea. Since `Exception` is the superclass of all exceptions, everything will get silently ignored! And it will be difficult to figure out later on if something is wrong with your code.

This practice is such a notoriously bad practice that there is a name for it -- [The Pokemon Exception Handling](https://wiki.c2.com/?PokemonExceptionHandling).

**Comment by andrewtkh1** [comment]
My solution to that was to use

```
try {
  // your code
} catch (Exception e) {
  print("Error :" + e)
}
```
As this would allow the user/me to still know what error is thrown. Or if need be, there is the `e.printStackTrace()` that would show which line it is at.

**Comment by richwill28** [comment]
> ```
> try {
>   // your code
> } catch (Exception e) {
>   print("Error :" + e)
> }
> ```

This is slightly better than swallowing all the exceptions. But by doing this, you are unable to handle them properly. For example, your code can catch both `FileNotFoundException` and `NullPointerException`, but you will probably want your program to react to them differently by using multiple `catch` blocks. Generally, the rule of thumb is to catch all the exceptions that you **expect**. So if you managed to catch something that you didn't expect, it is most definitely an indication that your code is buggy.

**Comment by okkhoy** [comment]
Consider a scenario where you are reading from a file.
The operation can go wrong for a few reasons, let's consider just 2 for our understanding.
1. The file you are trying to read is no present in the first place
2. The file read operation errored out (for whatever reason other than 1 above)

In this case,  you may want :

```
try {

} catch (FileNotFoundException fnfe) {
    // do something about the file
} catch (IOException  ioe) {
    // do something about i/o error
} catch (Exception e) {
    // this is something else that you never thought of!!
} finally {
    // here you clean up the mess, if any (e.g., close files/database handles/release network sockets etc.,)
}
```

In general, it is best to catch the most specific exception first, followed by the more general ones.
In the above example, `Exception` is the most generic; `IOException` and `FileNotFoundException` are its subclasses.
Further, `FileNotFoundException` is a subclass of  `IOException`. So we are going from most specific to most generic in the exception handling.

Hope that helps!


Note:
- It is generally code smell to catch an exception and do nothing - I call it a crime 😜 
- Catching an exception and printing stack trace follows in the severity - A lesser crime
- Catching an exception and printing the generic message - better but still bad
- Catching an exception and printing a specific message - much better
- Catching an exception and _really_ doing something about it - the best

@richwill28 's comment: 💯 :

>  ... you will probably want your program to react to them differently by using multiple catch blocks. Generally, the rule of thumb is to catch all the exceptions that you expect. So if you managed to catch something that you didn't expect, it is most definitely an indication that your code is buggy.
