### ISSUE TITLE
branch-A-Packages overdue iP dashboard

### ISSUE THREAD

**Issue by nvbinh15** [nus-cs2113-AY2122S1/forum#64]
Hi, Prof. 

The iP description of week 5 section 3 (Add Increment: `A-Packages`) specifies: 
"Recommended: if you are new to git, do this as a separate branch too (for additional practice), similar to how you did `Level-5` (branch name `branch-A-Packages`)."

To my understanding, `branch-A-Packages` should not be a requirement, and it was not included in the iP progress dashboard last week. However, when I check the dashboard again today, there is `branch-A-Packages` in the Admin tasks and there are a lot of students having this task overdue.

Could you please check this again?

**Comment by okkhoy** [comment]
please drop me a message with all the details I requested (as a standing instruction) in one of the previous lectures.
