### ISSUE TITLE
Text-ui-testing not catching exceptions that work when manually input

### ISSUE THREAD

**Issue by JMattChiam** [nus-cs2113-AY2122S1/forum#65]
Hi all

I'm running into an issue when trying to update the text-ui testing. For some reason, when using the automated testing, some exceptions are not being caught and are stopping the program. But when I run the same input on command line, responds correctly.

Here is the code for the try-catch:

![image](https://user-images.githubusercontent.com/69444734/132969598-632571c3-77ce-4178-a9d6-41cf56c9f510.png)

Just in the case where the input is "done" where the entry number is missing:
Running on command line and manually putting in the input works and gets the correct response:

![image](https://user-images.githubusercontent.com/69444734/132969616-7d2b8843-af2b-48e2-b915-1b02c033ce10.png)

but running the automated testing with just "done" in input.txt:

![image](https://user-images.githubusercontent.com/69444734/132969657-cca25a0c-0f07-4f86-800e-6ae7f117cf17.png)
The exception that causes the program to stop should have been caught by the catch block, as it does when manually input. 

Any ideas what's going wrong? Other try-catch blocks work both with manual and automated testing. Only this block seems to have problems.

Thanks!

**Comment by IshaaanVyas** [comment]
Sorry, this might not be very useful but I have experienced a similar issue and what I found out was that runtest.bat was running an outdated version of Duke (the version before I divided all the files into packages), maybe you could post your runtest.bat? In my case changing `java Duke` to `java duke.Duke` worked out fine.

**Comment by JMattChiam** [comment]
Thanks! Edited the class path and it works! I'm curious though, since the duke class file location has changed, wouldn't runtest.bat just not be able to find the file and throw and exception?

**Comment by IshaaanVyas** [comment]
In my case, after dividing it into packages the compiled output was also split into folders in the bin folder such as below
![image](https://user-images.githubusercontent.com/69447416/132970840-ac8c0832-aa84-4ab2-ad85-c0c796042d3d.png)
However, as you can see in the image the previous Duke was not deleted and it stayed there so when I ran `java Duke`  the outdated version ran instead of the one divided into packages/folders
