### ISSUE TITLE
Use of JSON files instead of txt files to store data

### ISSUE THREAD

**Issue by jonathanmui4** [nus-cs2113-AY2122S1/forum#66]
Hi, I was wondering if we are allowed to read and write data from json files instead of txt files?

**Comment by okkhoy** [comment]
Yes, JSON, CSV, plain text, XML, all are allowed. Just please ensure that the [constraint on human editability](https://nus-cs2113-ay2122s1.github.io/website/admin/tp-constraints.html#constraint-human-editable-file) is not violated.
