### ISSUE TITLE
💡 Removing pesky wildcard imports in IntelliJ IDEA

### ISSUE THREAD

**Issue by richwill28** [nus-cs2113-AY2122S1/forum#68]
According to our [coding standard](https://se-education.org/guides/conventions/java/index.html#package-and-import-statements):

![standard](https://user-images.githubusercontent.com/69445142/133127183-e943e0ee-8f31-4edc-bbb0-fed76bfbd92e.png)

I was doing iP when I noticed that IntelliJ IDEA combine all imports by default, every time I save my file. Frustrated, I decided to find a way to get around this problem. So I would like to share it here.

![guide](https://user-images.githubusercontent.com/69445142/133129137-b3cc49cb-2b39-494d-9267-f809f96d2046.png)

1. If you're on Windows, go to `File > Settings > Editor > Code Style > Java > Imports`
Note: Mac might be slightly different
2. Set `Class count to use import with '*'` to a high value
3. Also set `Names count to use static import with '*'` to a high value
4. Make sure to remove the two entries under `Packages to Use Import with '*'`
5. Apply

**Comment by okkhoy** [comment]
Nice catch! I was talking about something wrong in the previous lecture. I hadn't noticed the count thingy.

**Comment by richwill28** [comment]
Closing this issue to keep the forum clean.
