### ISSUE TITLE
Comments for IP

### ISSUE THREAD

**Issue by AnShengLee** [nus-cs2113-AY2122S1/forum#70]
Hi all, are comments necessary for IP?

**Comment by richwill28** [comment]
Yes, according to our [coding standard](https://se-education.org/guides/conventions/java/index.html#comments).

![comments](https://user-images.githubusercontent.com/69445142/133241893-ba93671e-e4d1-4344-98a2-f429685d28b6.png)

Well, even if you are not doing school assignments, it is a good practice to document all your codes anyway.

> “Programs are meant to be read by humans and only incidentally for computers to execute.” - Donald E. Knuth

Without comments or any kinds of documentation, your code will be difficult to maintain, extend, and reuse by others. Lastly, your future self will also thank you for documenting everything that you write.

**Comment by KishorKumar11** [comment]
It is an excellent practice to add comments from the start of any project, not only for others to understand, but for you too!
However, I believe its implementation is officially taught to us on Week 7.

**Comment by AnShengLee** [comment]
Alright thanks all.
