### ISSUE TITLE
Level-7: Save

### ISSUE THREAD

**Issue by xRossKoh** [nus-cs2113-AY2122S1/forum#71]
Is it necessary to change the text file every time a task, done or delete command is executed? Or can we just do one overwrite and save to the text file each time just before we exit the programme?

**Comment by okkhoy** [comment]
> `Save the tasks in the hard disk automatically whenever the task list changes. Load the data from the hard disk when Duke starts up`

The reason is to ensure data integrity in the event your Duke crashes.
