### ISSUE TITLE
What is the benefit of using static import over regular import?

### ISSUE THREAD

**Issue by richwill28** [nus-cs2113-AY2122S1/forum#75]
From the [official documentation](https://docs.oracle.com/javase/specs/jls/se11/html/jls-7.html#jls-7.5.3),
> A single-static-import declaration imports all accessible static members with a given simple name from a type.

I understand that static import allows us to pick certain static members from classes, without having to type the class qualifications. However, could this potentially harm the readability of our code? I'm wondering if it is just for syntactic sugar. Anyone have any thoughts on this?

**Comment by okkhoy** [comment]
For certain things static import may be useful (e.g., your own custom utilities class with all static methods), but it may be better to fully qualify the imports to understand where the mess is coming from (if a mess happens).

**Comment by richwill28** [comment]
Closing this issue to keep the forum clean.
