### ISSUE TITLE
Exceptions in Javadoc

### ISSUE THREAD

**Issue by richwill28** [nus-cs2113-AY2122S1/forum#78]
I came across these two interesting articles.

1. [Avoid @throws in javadoc](http://www.javapractices.com/topic/TopicAction.do?Id=171)
2. [Javadoc all exceptions](http://www.javapractices.com/topic/TopicAction.do?Id=44)

One argues that `@throws` should be used sparingly while the other recommends the opposite. I can't seem to find a general consensus about this anywhere else. Would like to hear your thoughts regarding this.

**Comment by richwill28** [comment]
P.S. I think the label `for-Discussion 💬` is more appropriate for this issue, but I don't have the access to edit it.

**Comment by okkhoy** [comment]
You need to document your checked exceptions. The key thing is don't leave the `@throws` without a description.
When we see the method signature, we know what is thrown. The person using your class (or library) should know why it is being thrown.

**Comment by richwill28** [comment]
> When we see the method signature, we know what is thrown. The person using your class (or library) should know why it is being thrown.

Ah this makes sense. I think this relates back to the concept that a good documentation should explain the *what* and *why*, rather than the *how*, as explained [here](https://nus-cs2113-ay2122s1.github.io/website/se-book-adapted/chapters/codeQuality.html#explain-what-and-why-not-how).

**Comment by richwill28** [comment]
Closing this issue to keep the forum clean.
