### ISSUE TITLE
Unmerging a branch after push.

### ISSUE THREAD

**Issue by WaiKit-nus** [nus-cs2113-AY2122S1/forum#85]
Hi,

I am currently working on my IP and I forgot to do a pull request for A-javadoc branch and simply merged it and pushed it to github. I would like to know how can I revert this merge for A-javadoc and perform the required pull request needed. An SS of my tree is below.
![image](https://user-images.githubusercontent.com/80661630/135295818-891adb6b-e12b-4fef-8807-9c04667b59cd.png)

I saw this method (attached below) and am unsure if it will work. In short, it suggests to hard-reset my master branch to a commit before the merge & then use `git push origin master --force-with-lease` to push my master branch into GH. Does anyone know if this will work? Also, is it ok to use `--force-with-lease` or should I avoid it?
Link to the method: https://stackoverflow.com/questions/14308580/undo-a-fast-forward-merge/14308631#14308631

Thanks!

**Comment by okkhoy** [comment]
Discussed during the tutorial! Please ping me on MSTeams if you need further help.
