### ISSUE TITLE
Week 6, A-Jar tag was not detected

### ISSUE THREAD

**Issue by andrewtkh1** [nus-cs2113-AY2122S1/forum#87]
Hi Sir,

I just saw that the script did not detect my week 6's A-Jar tag even though I submitted it on time, how should i go about resolving this?

![image](https://user-images.githubusercontent.com/69303287/135366768-55703407-55be-4494-b8a7-fcd09fc10a1f.png)
![image](https://user-images.githubusercontent.com/69303287/135366883-6f4fff58-d8b3-4936-a992-6983adebb335.png)

**Comment by okkhoy** [comment]
resolved in tutorial 😜
