### ISSUE TITLE
Better way to checking multiple `instanceof`

### ISSUE THREAD

**Issue by richwill28** [nus-cs2113-AY2122S1/forum#89]
Let's say I have a class `Animal` which will be the parent class of all animals (duh!). For example, consider the following code. 

```java
class Animal {
    // ...
}

class Parrot extends Animal {
    // ...

    int fly() {
        // ...
    }
}

class Eagle extends Animal {
    // ...

    int fly() {
        // ...
    }
}

class Bat extends Animal {
    // ...

    int fly() {
        // ...
    }
}

// ...etc
```

Note: The `fly` method returns the velocity of said animal while flying.

Now here comes the problem. Suppose I have a list of animals object `ListOfAnimals`, and I want to filter out every animal that can fly with a velocity of, say, more than a certain variable `v`. I can think of several ways to do this.

1. **Using multiple `if-else`**

```java
public List<Animal> filterAnimalByVelocity(int v) {
    List<Animal> filteredListOfAnimals = new ArrayList<>();

    for (Animal animal : ListOfAnimals) {
        if (animal instanceof Parrot) {
            Parrot parrot = (Parrot) animal;
            if (parrot.fly() > v) {
                filteredListOfAnimals.add(parrot);
            }
        } else if (animal instanceof Eagle) {
            // ...do something similar
        } else if (animal instanceof Bat) {
            // ...do something similar
        }
        // ...repeat else if for all other animals that can fly
    }

    return filteredListOfAnimals;
}
```

The above solution certainly works, but it is not scalable. When I add a new class of animal that can fly, I have to modify this function.

2. **Create a `Bird` class**

The rationale for doing this is to cast an instance to `Bird` whenever possible, so we can execute the `fly` method. However, my problem with this solution is that not every bird can fly, and that other animals that are not bird can also fly too (e.g. bat).

3. **Create a `Flyable` interface**

Every animal that can fly must implement this interface. So I just need to check if an animal object is a subclass of `Flyable`. This idea sounds great to me, but unfortunately it doesn't work.

```java
public List<Animal> filterAnimalByVelocity(int v) {
    List<Animal> filteredListOfAnimals = new ArrayList<>();

    for (Animal animal : ListOfAnimals) {
        if (animal instanceof Flyable) {
            Flyable flyingAnimal = (Flyable) animal;    // compile-time error
            if (flyingAnimal.fly() > v) {
                filteredListOfAnimals.add(flyingAnimal);
            }
        }
    }

    return filteredListOfAnimals;
}
```

So here is my question. Is there a better way of doing this, rather than just checking `instanceof` in multiple `if-else`?

**Comment by okkhoy** [comment]
If your intention is: "and I want to filter out every animal that can fly with a velocity of, say, more than a certain variable `v`", you don't really need instance-of checks, no?
Iterate through the list of animals and filter/add them to a new list based on your condition.

If your intention is to do some other processing pertaining to each individual class, there is nothing much we can do other than use individual instance-of.  
You can refactor code such that you have one method to process one kinda object. 

Does it (👆) make sense?

**Comment by richwill28** [comment]
> you don't really need instance-of checks, no? Iterate through the list of animals and filter/add them to a new list based on your condition.

But not all animals have the `fly` method. I don't think we can just check the condition immediately?

**Comment by okkhoy** [comment]
Your method 3 seems to work with aminor tweak. See below?

```
    public static ArrayList<Animal> filterAnimalsByVelocity(int v, Animal[] allAnimals) {
        ArrayList<Animal> filteredAnimals = new ArrayList<>();
        for (Animal a : allAnimals) {
            if (a instanceof Flyable) {
                Flyable f = (Flyable) a;
                if (f.fly() > v) {
                    filteredAnimals.add(a);
                }
            }
        }
        return filteredAnimals;
    }
```

Attached project:  [AnimalTest.zip](https://github.com/nus-cs2113-AY2122S1/forum/files/7257548/AnimalTest.zip)

**Comment by richwill28** [comment]
@okkhoy Ah yes, it does work. I thought the problem was this particular line, `Flyable flyingAnimal = (Flyable) animal`. But why doing `filteredAnimals.add(a)` is okay, but `filteredAnimals.add(f)` is not? Shouldn't both variables reference the same object?

**Comment by richwill28** [comment]
> If your intention is to do some other processing pertaining to each individual class, there is nothing much we can do other than use individual instance-of. You can refactor code such that you have one method to process one kinda object.

So is it correct to say that, using multiple `instanceof` does not necessarily means code smell?

**Comment by okkhoy** [comment]
> why doing `filteredAnimals.add(a)` is okay, but `filteredAnimals.add(f)` is not?

'cos your `filteredAnimals` is an array list of type `Animal` and not `Flyable`. There is no correct route to cast it.
If you wish to add `Flyable` then create the the array list of type `Flyable` and can then add `f`.

> is it correct to say that, using multiple `instanceof `does not necessarily means code smell?

I didn't say that 😛 There are times when we may have to use `instanceof`; in such scenarios we have to use it as no other go. However, it may be better to minimize it, as much as possible -- if possible!

**Comment by richwill28** [comment]
Ah ok. Thanks for clarifying. 👍
