### ISSUE TITLE
Request to use third-party library - JsonPath

### ISSUE THREAD

**Issue by yeezao** [nus-cs2113-AY2122S1/forum#91]
## Library

[JsonPath](https://github.com/json-path/JsonPath)

## Purpose

To parse JSON strings to populate objects

## License

Apache License 2.0
https://github.com/json-path/JsonPath/blob/master/LICENSE

**Comment by okkhoy** [comment]
Hmmm... JsonPath borders ORM and query-language-like structures. (e.g., finding all authors) which is not allowed in this module.
Please find an alternative way to use Json in your project.
This library is not approved.
