### ISSUE TITLE
Quiz 8 Clarification

### ISSUE THREAD

**Issue by mudkip8** [nus-cs2113-AY2122S1/forum#92]
For question 2, the one with the purple Student class, is `calculateCAP()` not a class-level method?

**Comment by richwill28** [comment]
> In UML class diagrams, **underlines denote class-level attributes and variables.**

[Source](https://nus-cs2113-ay2122s1.github.io/website/book/uml/classDiagrams/classLevelMembers/what/)

**Comment by mudkip8** [comment]
Ah Ok. Thanks!
