### ISSUE TITLE
tP Progress Tracker - incorrect date range

### ISSUE THREAD

**Issue by yeezao** [nus-cs2113-AY2122S1/forum#93]
Hi prof,

I noticed that the date range for this week's commits (under individual tracker) in the tP progress tracker is wrong (after clicking the more information button) - picture attached:

![image](https://user-images.githubusercontent.com/61348279/135823356-56878c20-cfdc-418c-9b98-e852e2c48253.png)

**Comment by okkhoy** [comment]
Ah! Good catch. Let me get it fixed. Thanks!
