### ISSUE TITLE
Request to use iCal4j

### ISSUE THREAD

**Issue by SuibianP** [nus-cs2113-AY2122S1/forum#94]
## Library

[iCal4j](https://github.com/ical4j/ical4j)

## Purpose
To serialise and deserialisation [iCalendar](https://en.wikipedia.org/wiki/ICalendar) format. This is to use a well-tested format instead of our ad-hoc one. As a bonus, this makes out application interoperable with most calendar applications.

## License

[BSD-3](https://github.com/ical4j/ical4j/blob/develop/LICENSE.txt)

**Comment by okkhoy** [comment]
Approved 👍
