### ISSUE TITLE
Trouble with CI Checks.

### ISSUE THREAD

**Issue by andrewtkh1** [nus-cs2113-AY2122S1/forum#95]
Hello everyone,

Does anyone happen to know why would my CI checks suddenly stop working?
I have double-checked my settings (below) and the number of checks are 0 despite the PR being ready to merge. Is anyone else having this issue too?

![image](https://user-images.githubusercontent.com/69303287/136039641-12fe1ccc-3784-48ff-814d-f222b993f537.png)
![image](https://user-images.githubusercontent.com/69303287/136039862-e2426059-e117-4d61-b251-ae016b79b674.png)

**Comment by richwill28** [comment]
What checks are you trying to run?

**Comment by andrewtkh1** [comment]
> 
> 
> What checks are you trying to run?

Like how when you create a PR, GH is supposed to automatically run the CI checks (e.g. Check styles).

**Comment by richwill28** [comment]
> (e.g. Check styles).

Hmm.. I'm not sure if this is enabled by default for the CI. Maybe @okkhoy can confirm?

For other checks that we currently have (at least for my team), are three of the followings:

![Capture](https://user-images.githubusercontent.com/69445142/136045105-1575cf3e-3129-4b2c-9bd3-75d35a1a18f2.PNG)

You can configure them to be required under the branch protection rule.

![Capture](https://user-images.githubusercontent.com/69445142/136045349-4315b437-d74a-41d6-b054-f4b6526a367b.PNG)

**Comment by okkhoy** [comment]
Jointly we suspect: 
![image](https://user-images.githubusercontent.com/1023494/136055153-1662c9a2-4989-4dd0-b0ef-8ea7f143fbdd.png)

lets 🤞 and wait for it to get resolved

**Comment by richwill28** [comment]
> Jointly we suspect: ![image](https://user-images.githubusercontent.com/1023494/136055153-1662c9a2-4989-4dd0-b0ef-8ea7f143fbdd.png)
> 
> lets 🤞 and wait for it to get resolved

Ah yes, am just about to comment on this since my CI is also stuck. 😅

Edit: Btw for anyone wondering the website is https://www.githubstatus.com/

**Comment by okkhoy** [comment]
haha... we just spent a good 1 hr 20 min trying to debug... hopefully it is just the GH Actions issue and nothing wrong with @andrewtkh1 's team repo..

**Comment by andrewtkh1** [comment]
Quick update, seems to be working now. Will try again with more PRs!
![image](https://user-images.githubusercontent.com/69303287/136059410-5e41a807-978b-41d4-8d74-5da8a777544d.png)

Thank you @okkhoy @richwill28 for your help!
