### ISSUE TITLE
Individual progress for tp dashboard not being updated.

### ISSUE THREAD

**Issue by theodorekwok** [nus-cs2113-AY2122S1/forum#96]
Hi Prof!, I noticed that under my individual progress activity v1.0 PRs, it is not being updated despite creating a PR in the team repo and assigning it to milestone v1.0. May I ask what should I do to resolve this issue? And does one need to tag the commit with 'v1.0 PRs' to resolve it?

**Comment by okkhoy** [comment]
For this, please drop me an email with your student number, GitHub username, team repo link.

**Comment by theodorekwok** [comment]
Sry prof, I just refreshed and the dashboard is updated
