### ISSUE TITLE
dos2unix command not found error

### ISSUE THREAD

**Issue by Nirmaleshwar** [nus-cs2113-AY2122S1/forum#98]
![Screenshot (83)](https://user-images.githubusercontent.com/77761339/136371503-eac7bee2-4ff3-4e9d-bb77-382b6d28d8e7.png)

Hi, for some reason when I run the Gradle tests, I'm getting this error. I haven't made any changes to the sh file but, it says dos2unix command not found. May I know how to rectify this?

**Comment by Nirmaleshwar** [comment]
No worries I fixed the problem

**Comment by richwill28** [comment]
> No worries I fixed the problem

Well.. just gonna say maybe it's better if you also explain how you solved the problem and don't leave the thread hanging. Others might face the same issue as well. 😉

**Comment by Nirmaleshwar** [comment]
Oh I realized the issue I had mentioned wasn't the problem. It was something to do with my code, I had mistakenly called the printBye() method twice so the actual and expected output's didn't match.

**Comment by Nirmaleshwar** [comment]
Oh I realized the issue I had mentioned wasn't the problem. It was something to do with my code, I had mistakenly called the printBye() method twice so the actual and expected output's didn't match.
