### ISSUE TITLE
GitHub Actions not stopping.

### ISSUE THREAD

**Issue by andrewtkh1** [nus-cs2113-AY2122S1/forum#99]
Hi Sir,

I accidentally forgot to key in any inputs for my IO-redirect test but had some stuff in the expected file. Now the checks wouldn't stop running. I'm not sure if its a bug or what but just thought it would be best to inform you. I fixed it by simply re-pushing with something filled in the "input.txt" file and stopping the old checks.

Below is part of the logs output that it keeps giving me, not sure if its of any help.

![image](https://user-images.githubusercontent.com/69303287/136790126-a14fdd21-4b40-44d8-9501-d2c8c824bc47.png)

**Comment by okkhoy** [comment]
just cancel the run.
did this occur on your machine when you tested?

**Comment by andrewtkh1** [comment]
Just tried it & it gives the same issues. My bad...

Thank you!

**Comment by okkhoy** [comment]
> Just tried it & it gives the same issues. My bad...

on your machine?

**Comment by DuckWillow** [comment]
![image](https://user-images.githubusercontent.com/71874189/137302101-dfa66929-9614-47cd-a187-a4eed0b4737a.png)
I am having the same problem here. Once I run 'runtest.sh', it keeps showing 'No Line Found'.

I have already added the input and expected output texts.
![image](https://user-images.githubusercontent.com/71874189/137303619-d8baf0ae-4ad6-4e00-82b7-b589c2033637.png)
It shows execution failed for task ' clean'.

**Comment by DuckWillow** [comment]
So I solved the problem by using this website:
https://www.eknori.de/2020-09-18/gradle-execution-failed-for-task-appclean-unable-to-delete-file/

@andrewtkh1 You need to type 'TASKKILL /F /IM java.exe' in the terminal to kill all previous runtest.sh.
Then make sure the input text matches the expected text.

![image](https://user-images.githubusercontent.com/71874189/137315849-3912bc55-4f75-43c6-8f1c-04f83797fb93.png)
